apiVersion: v1
kind: Pod
metadata:
  name: missing-secret-public-image
  namespace: imagepullbackoff-lab
  labels:
    app: imagepullbackoff-demo
    edge-case: missing-pull-secret
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: does-not-exist
  containers:
    - name: web
      image: nginx:1.27-alpine
      imagePullPolicy: Always
